### ISSUE TITLE
SCSSとは

### ISSUE THREAD

**Issue by IHprogram** [IHprogram/js-study#2]
### SCSSとは？
SCSSは、Rubyで開発された、CSSを拡張したメタ言語。
CSSを効率的に記述できるように設計、開発された。

大きな特徴としては以下の通り。
- ネスト（入れ子）により、記述量を減らすことができる
- 変数や関数を使用できる
- mixin（スタイルを再利用する機能）を利用できる

### コンパイル
SCSS/SASSで記述したコードはそのままでは使用できず、CSSにコンパイルしなければならない。

今回はVSCodeの拡張機能「Live Sass Compiler」を使用。

以下のようにSCSSのコードはCSSのコードにコンパイルされる。

```scss: SCSSの場合
.parent {
    background-color: #ffffff;
    .child {
        color: #000000;
    }
}
```

```css: CSSの場合
.parent {
    background-color: #ffffff;
}

.parent .child {
    color: #000000;
}
```

### 変数
「$変数名: 値;」と書くことで、変数を定義できる。

```scss: 例
$green: #008000;

// 下記は「green-text」というクラス名の要素の文字色と「main-container」というクラス名の要素の背景色を緑色にしている

.green-text {
    color: $green;
}

.main-container {
    background-color: $green;
}
```

### 関数
「@function 関数名($引数){ @return 処理 }」と書くことで、関数を定義できる。

```scss: 例
// 受け取った数値を2倍にして返す関数
@function doubleFunc($num){
    @return $num * 2;
};

// 下記の場合、「main-container」というクラス名の要素の横幅は200px、高さは400pxになる
.main-container {
    width: doubleFunc(100px);
    height: doubleFunc(200px);
}
```

### mixin(ミックスイン)
「@mixin」でスタイルを定義し、@includeで呼び出すことで、定義したスタイルを呼び出すことができる。

```scss: 例

// 要素の横幅、高さ、背景色を決めるミックスイン。「横幅100px、高さ100px、背景色は白色」という初期値を設定している
@mixin boxFunc($boxWidth: 100px, $boxHeight: 100px,$backgroundColor:#ffffff) {
    width: $boxWidth;
    height: $boxHeight;
    background-color: $backgroundColor;
}

// @includeで呼び出し。以下の場合、要素は「横幅200px、高さ200px、背景色は黒色」となる
.main-container {
    @include boxFunc(200px, 200px, #000000)
}
